site_name: Sergio

<<<<<<< HEAD
theme:
  name: readthedocs
  nav_style: dark

nav:
  - Inicio: "index.md"
  - Documentacion: "documentacion.md"
=======
nav:
  - Inicio: "index.md"
>>>>>>> 00b3354f83da93ef6e846b9eb6890e09dad4e161
